automation:
  # Opening front door or patio door will trigger alarm
  - alias: Alarm Control Panel Trigger All
    trigger:
      - platform: state
        entity_id:
          - input_boolean.alarm_control_panel_trigger
          - binary_sensor.door_sensor_2
          - binary_sensor.door_sensor_3
        to: "on"
    condition:
      - condition: template
        value_template: >-
          {{ states("alarm_control_panel.home_alarm") != "disarmed" }}
      - condition: state
        entity_id: input_boolean.in_home_services
        state: "off"
    action:
      - service: alarm_control_panel.alarm_trigger
        entity_id: alarm_control_panel.home_alarm

  - alias: Alarm Control Panel Trigger All Service Present
    trigger:
      - platform: state
        entity_id:
          - input_boolean.alarm_control_panel_trigger
          - binary_sensor.door_sensor_2
          - binary_sensor.door_sensor_3
        to: "on"
    condition:
      - condition: template
        value_template: >-
          {{ states("alarm_control_panel.home_alarm") != "disarmed" }}
      - condition: state
        entity_id: input_boolean.in_home_services
        state: "on"
    action:
      - service: alarm_control_panel.alarm_disarm
        entity_id: alarm_control_panel.home_alarm

  # Motion in the house will trigger alarm when set to away
  - alias: Alarm Control Panel Trigger Away
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.door_sensor_1
          - binary_sensor.motion_camille_bedroom
          - binary_sensor.motion_hallway
          - binary_sensor.motion_living_room
          - binary_sensor.motion_office
          - binary_sensor.motion_master_bedroom
        to: 'on'
    condition:
      - condition: template
        value_template: >-
         {{ states("alarm_control_panel.home_alarm") == "armed_away" }}
    action:
      - service: alarm_control_panel.alarm_trigger
        entity_id: alarm_control_panel.home_alarm

  - alias: Alarm Arm Night Buttons
    trigger:
      - platform: state
        entity_id:
          - input_boolean.minimote_master_bedroom_2
          - input_boolean.flic_button_hold
    condition:
      - condition: template
        value_template: >-
          {{ states("alarm_control_panel.home_alarm") == "disarmed" }}
    action:
      - service: alarm_control_panel.alarm_arm_night
        entity_id: alarm_control_panel.home_alarm

  - alias: Alarm Arm Away Buttons
    trigger:
      - platform: state
        entity_id:
         - input_boolean.minimote_front_door_2
    condition:
      - condition: template
        value_template: >-
          {{ states("alarm_control_panel.home_alarm") == "disarmed" }}
    action:
      - service: alarm_control_panel.alarm_arm_away
        entity_id: alarm_control_panel.home_alarm

  - alias: Alarm Disarm Buttons
    trigger:
      - platform: state
        entity_id:
          - input_boolean.minimote_master_bedroom_8
          - input_boolean.minimote_front_door_8
          - input_boolean.flic_button_single_click
    condition:
      - condition: template
        value_template: >-
          {{ states("alarm_control_panel.home_alarm") != "disarmed" }}
    action:
      - service: alarm_control_panel.alarm_disarm
        entity_id: alarm_control_panel.home_alarm
<<<<<<< HEAD
      - service: input_boolean.turn_off
        entity_id: input_boolean.in_home_services
=======
      - service: media_player.media_pause
        data:
          entity_id:
            - media_player.bedroom_speaker
            - media_player.living_room_display
>>>>>>> 1e9bcd0cf979eef5869b782f1ba35efafc0c1e59

  - alias: Alarm Disarm When Triggered
    trigger:
      - platform: state
        entity_id:
          - input_boolean.minimote_master_bedroom_1
          - input_boolean.minimote_master_bedroom_2
          - input_boolean.minimote_master_bedroom_3
          - input_boolean.minimote_master_bedroom_4
          - input_boolean.minimote_master_bedroom_5
          - input_boolean.minimote_master_bedroom_6
          - input_boolean.minimote_master_bedroom_7
          - input_boolean.minimote_master_bedroom_8
          - input_boolean.minimote_front_door_8
          - input_boolean.flic_button_single_click
          - input_boolean.flic_button_hold
    condition:
      - condition: template
        value_template: >-
          {{ states("alarm_control_panel.home_alarm") == "triggered" }}
    action:
      - service: alarm_control_panel.alarm_disarm
        entity_id: alarm_control_panel.home_alarm
      - service: switch.turn_off
        entity_id: switch.linear_unknown_type_2005_id_0503_switch
<<<<<<< HEAD
      - service: input_boolean.turn_off
        entity_id: input_boolean.in_home_services
=======
      - service: media_player.media_pause
        data:
          entity_id:
            - media_player.bedroom_speaker
            - media_player.living_room_display
>>>>>>> 1e9bcd0cf979eef5869b782f1ba35efafc0c1e59

  # Keep arlo alarm states in sync with manual alarm panel
  - alias: Aarlo alarm set from main alarm
    trigger:
      - platform: state
        entity_id: alarm_control_panel.home_alarm
    condition:
      - condition: template
        value_template: >-
          {{ states("alarm_control_panel.home_alarm") != "pending" or
             states("alarm_control_panel.home_alarm") != "triggered"}}
    action:
      - entity_id: alarm_control_panel.aarlo_lancaster
        service_template: >-
          {% if trigger.to_state.state == "armed_home" %}
          alarm_control_panel.alarm_arm_home
          {% elif trigger.to_state.state == "armed_night" %}
          alarm_control_panel.alarm_arm_night
          {% elif trigger.to_state.state == "armed_away" %}
          alarm_control_panel.alarm_arm_away
          {% elif is_state("input_boolean.in_home_services", "on") %}
          alarm_control_panel.alarm_arm_away
          {% else %}
          alarm_control_panel.alarm_disarm
          {% endif %}
