binary_sensor:
  - platform: template
    sensors:
        door_sensor_1:
          device_class: opening
          friendly_name: "Master Closet Door"
          value_template: >-
            {{ states("binary_sensor.wadwaz_1_door_window_sensor_sensor_2") == 'on'}}
        door_sensor_2:
          device_class: opening
          friendly_name: "Front Door"
          value_template: >-
            {{ states("binary_sensor.wadwaz_1_door_window_sensor_sensor_3") == 'on'}}
        door_sensor_3:
          device_class: opening
          friendly_name: "Laundry Closet Door"
          value_template: >-
            {{ states("binary_sensor.wadwaz_1_door_window_sensor_sensor") == 'on'}}
        door_sensor_4:
          device_class: opening
          friendly_name: "Front Closet Door"
          value_template: >-
            {{ states("binary_sensor.wadwaz_1_door_window_sensor_sensor_4") == 'on'}}
        door_sensor_5:
          device_class: opening
          friendly_name: "Kitchen Cabinet Door"
          value_template: >-
            {{ states("binary_sensor.wadwaz_1_door_window_sensor_sensor_5") == 'on'}}

input_boolean:
  door_alert_delay:
    name: Door Alert Delay
    icon: mdi:bell-off
    initial: off

group:
  door_sensors:
    name: "All Door Sensors"
    entities:
      - binary_sensor.door_sensor_1
      - binary_sensor.door_sensor_2
      - binary_sensor.door_sensor_3
      - binary_sensor.door_sensor_4