automation:
  - alias: "Door Alert Mary Asleep"
    trigger:
      platform: state
      entity_id: binary_sensor.door_sensor_1
      to: "on"
    condition:
      - condition: state
        entity_id: alarm_control_panel.home_alarm
        state: "armed_night"
    action:
      service: tts.google_say
      entity_id:
        - media_player.living_room_display
        - media_player.bedroom_speaker
      data:
        message: "Alert, Mary's door is open. Alert, Mary's Door is open"

  - alias: "Notify Door"
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.door_sensor_1
          - binary_sensor.door_sensor_2
          - binary_sensor.door_sensor_3
        to: "on"
      - platform: state
        entity_id: binary_sensor.door_sensor_1
        to: "off"
    condition:
      - condition: state
        entity_id: input_boolean.door_alert_delay
        state: "off"
    action:
      - service: notify.notify
        data_template:
          title: "Door Alert"
          message: >-
            {{ state_attr(trigger.entity_id, "friendly_name") }} is{%
            if is_state(trigger.entity_id, "on") %} open {% else %} closed {% endif %}

  - alias: "Notify Alarm Triggered"
    trigger:
      - platform: state
        entity_id: alarm_control_panel.home_alarm
        to: "triggered"
    action:
      # - service: switch.turn_on
      #   data:
      #     entity_id: switch.linear_unknown_type_2005_id_0503_switch
      - service: tts.google_say
        entity_id:
          - media_player.living_room_display
          - media_player.bedroom_speaker
        data:
          message: "Alert, Alarm Triggered. Alert, Alarm Triggered"
      - service: notify.notify
        data:
          title: "Alarm"
          message: "Triggered"

  - alias: "Turn On Door Delay"
    trigger:
      - platform: state
        entity_id:
          - input_boolean.minimote_front_door_8
          - input_boolean.minimote_master_bedroom_8
    action:
      - service: homeassistant.turn_on
        entity_id: input_boolean.door_alert_delay

  - alias: "Reset Door Delay"
    trigger:
      - platform: state
        entity_id: input_boolean.door_alert_delay
        to: "on"
    action:
      - service: script.turn_on
        entity_id: script.reset_door_delay

  - alias: Notify Motion Mary
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_mary_bedroom
        to: "on"
    condition:
      - condition: template
        value_template: >-
          {{ states("input_select.mary_status") == "Asleep" }}
    action:
      - service: notify.notify
        data:
          title: "Motion Alert"
          message: "Mary's Bedroom"

  - alias: Notify All Motion
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.motion_camille_bedroom
          - binary_sensor.motion_hallway
          - binary_sensor.motion_living_room
          - binary_sensor.motion_mary_bedroom
          - binary_sensor.motion_master_bedroom
        to: "on"
    condition:
      - condition: state
        entity_id: alarm_control_panel.home_alarm
        state: "armed_night"
    action:
      - service: notify.ios_ergisch
        data_template:
          title: "Motion Alert"
          message: >-
            {{ state_attr(trigger.entity_id, "friendly_name") }}

script:
  reset_door_delay:
    alias: Reset the door delay
    sequence:
      - delay:
          seconds: 15
      - service: input_boolean.turn_off
        data:
          entity_id:
            - input_boolean.door_alert_delay

  door_alert_delay:
    alias: Delay front door alert
    sequence:
      - service: input_boolean.turn_on
        data:
          entity_id:
            - input_boolean.door_alert_delay
