automation:
  - alias: "Notify Door"
    # Constantly send door status. Like all the time
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.door_sensor_1
          - binary_sensor.door_sensor_2
          - binary_sensor.door_sensor_3
        to: "on"
      - platform: state
        entity_id: binary_sensor.door_sensor_1
        to: "off"
    condition:
      - condition: state
        entity_id: input_boolean.door_alert_delay
        state: "off"
      - condition: template
        value_template: >-
          {{ not is_state("alarm_control_panel.home_alarm", "disarmed") }}
    action:
      - service: notify.notify
        data_template:
          title: "Door Alert"
          message: >-
            {{ state_attr(trigger.entity_id, "friendly_name") }} is{%
            if is_state(trigger.entity_id, "on") %} open {% else %} closed {% endif %}

  - alias: "Notify Alarm Triggered"
    # If the alarm is triggered, here is what happens. Set of the loud alarm as well has
    # have google get noisy
    trigger:
      - platform: state
        entity_id: alarm_control_panel.home_alarm
        to: "triggered"
    action:
      - service: switch.turn_on
        data:
          entity_id: switch.linear_unknown_type_2005_id_0503_switch
      - service: tts.google_translate_say
        entity_id:
          - media_player.living_room_display
          - media_player.bedroom_speaker
        data:
          message: "Alert, Alarm Triggered. Alert, Alarm Triggered"
      - service: notify.notify
        data:
          title: "Alarm"
          message: "Triggered"

  - alias: "Turn On Door Delay"
    # In case you want to sneak out without alerts going off
    trigger:
      - platform: state
        entity_id:
          - input_boolean.minimote_front_door_8
          - input_boolean.minimote_master_bedroom_8
    action:
      - service: homeassistant.turn_on
        entity_id: input_boolean.door_alert_delay

  - alias: "Reset Door Delay"
    # If the door alert delay is turned on, turn it off again
    trigger:
      - platform: state
        entity_id: input_boolean.door_alert_delay
        to: "on"
    action:
      - service: script.turn_on
        entity_id: script.reset_door_delay

  - alias: Notify All Motion
    # If the alarm is set, let michael know about motion
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.motion_camille_bedroom
          - binary_sensor.motion_hallway
          - binary_sensor.motion_living_room
          - binary_sensor.motion_office
          - binary_sensor.motion_master_bedroom
        to: "on"
    condition:
      - condition: state
        entity_id: alarm_control_panel.home_alarm
        state: "armed_night"
    action:
      - service: notify.security_verbose
        data_template:
          title: "Motion Alert"
          message: >-
            {{ state_attr(trigger.entity_id, "friendly_name") }}

  - alias: Notify Alarm State
    # Notify Michael as the alarm states change
    trigger:
      - platform: state
        entity_id: alarm_control_panel.home_alarm
    action:
      - service: notify.security_verbose
        data:
          title: "Alarm"
          message: >-
            {% set map = {"disarmed": "Disarmed",
                          "pending": "Pending",
                          "armed_away": "Away",
                          "armed_home": "Home",
                          "armed_night": "Night",
                          "triggered": "Triggered"} %}
            Set to {{ map[states("alarm_control_panel.home_alarm")] }}

  - alias: Notify Motion In Bedroom
    # Notify motion in bedroom when caregivers are the only ones here
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_master_bedroom
        to: "on"
    condition:
      - condition: template
        value_template: >-
          {{ states("person.angela") != "home" and
             states("person.michael") != "home" }}
    action:
      - service: tts.google_say
        entity_id:
          - media_player.bedroom_speaker
        data:
          message: "Stop. Do not enter. Go Back now."
      - service: notify.notify
        data:
          title: "Alarm"
          message: "Motion in Master Bedroom"

  - alias: Notify Pending Trigger
    trigger:
      - platform: state
        entity_id: alarm_control_panel.home_alarm
        from: "armed_away"
        to: "pending"
    action:
      - service: media_player.play_media
        data:
          entity_id:
            - media_player.bedroom_speaker
            - media_player.living_room_display
          media_content_id: "https://dl.dropbox.com/s/mwc2xralppy0cva/Ship_Brass_Bell-Mike_Koenig-1458750630.wav"
          media_content_type: "music"
      - service: notify.notify
        data:
          title: "Alarm"
          message: "Alarm will sound in 15 seconds"

script:
  reset_door_delay:
    # Wait 15 seconds then turn off the door notification delay
    alias: Reset the door delay
    sequence:
      - delay:
          seconds: 15
      - service: input_boolean.turn_off
        data:
          entity_id:
            - input_boolean.door_alert_delay

  door_alert_delay:
    # Turn on the door alert delay
    # TODO is this used?
    alias: Delay front door alert
    sequence:
      - service: input_boolean.turn_on
        data:
          entity_id:
            - input_boolean.door_alert_delay
