binary_sensor:
  - platform: template
    sensors:
      motion_office:
        device_class: motion
        friendly_name: "Office Motion"
        value_template: >-
          {{ states("sensor.linear_wapirz_1_motion_sensor_alarm_level")|float > 0 }}
      motion_hallway:
        device_class: motion
        friendly_name: "Hallway Motion"
        value_template: >-
          {{ states("sensor.linear_wapirz_1_motion_sensor_alarm_level_2")|float > 0 }}
      motion_camille_bedroom:
        device_class: motion
        friendly_name: "Camille's Bedroom Motion"
        value_template: >-
          {{ states("sensor.aeotec_dsb05_multisensor_battery_level") == "on" }}
      motion_living_room:
        device_class: motion
        friendly_name: "Living Room Motion"
        value_template: >-
          {{ states("sensor.linear_wapirz_1_motion_sensor_alarm_level_3")|float > 0 }}
      motion_master_bedroom:
        device_class: motion
        friendly_name: "Master Bedroom Motion"
        value_template: >-
          {{ states("sensor.aeotec_zw100_multisensor_6_battery_level") == "on" }}

group:
  motion_sensors:
    name: All Motion Sensors
    entities:
      # - binary_sensor.motion_office
      # - binary_sensor.motion_hallway
      - binary_sensor.motion_camille_bedroom
      # - binary_sensor.motion_living_room
      - binary_sensor.motion_master_bedroom
