aarlo:
  username: !secret arloUsername
  password: !secret arloPassword
  refresh_devices_every: 6

camera:
  - platform: aarlo
    ffmpeg_arguments: '-pred 1 -q:v 2'

alarm_control_panel:
  - platform: aarlo
    home_mode_name: Home
    away_mode_name: armed
    night_mode_name: Home

binary_sensor:
  - platform: aarlo
    monitored_conditions:
    - motion
    - sound
    # - ding

sensor:
  - platform: aarlo
    monitored_conditions:
    - last_capture
    - total_cameras
    - battery_level
    - captured_today
    - signal_strength

switch:
  - platform: aarlo
    snapshot: True
    siren: True
