# This is yaml copied from the "Edit Config" from the UI
# These settings are not live and need to be pasted back into the UI to take effect
resources:
  - type: module
    url: /local/aarlo-glance.js
title: Home
views:
  - badges: []
    cards:
      - entity: alarm_control_panel.home_alarm
        states:
          - arm_home
          - arm_away
          - arm_night
        type: alarm-panel
      - detail: 6
        entity: sensor.temperature_whole_house
        graph: line
        type: sensor
      - detail: 6A
        entity: sensor.humidity_whole_house
        graph: line
        type: sensor
      - type: vertical-stack
        cards:
          - type: glance
            entities:
              - entity: input_select.michael_status
              - entity: input_select.angela_status
              - entity: input_select.camille_status
          - type: history-graph
            entities:
              - entity: person.michael
              - entity: person.angela
              - entity: person.camille
      - card:
          entities:
            - entity: switch.linear_unknown_type_2005_id_0503_switch
          type: entities
        conditions:
          - entity: switch.linear_unknown_type_2005_id_0503_switch
            state: 'on'
        type: conditional
      - type: conditional
        conditions:
          - entity: media_player.living_room_tv
            state_not: 'off'
        card:
          type: media-control
          entity: media_player.living_room_tv
      - type: conditional
        conditions:
          - entity: media_player.living_room_display
            state_not: 'off'
        card:
          type: media-control
          entity: media_player.living_room_display
      - type: conditional
        conditions:
          - entity: media_player.bedroom_speaker
            state_not: 'off'
        card:
          type: media-control
          entity: media_player.bedroom_speaker
      - type: conditional
        conditions:
          - entity: media_player.camille_s_speaker
            state_not: 'off'
        card:
          type: media-control
          entity: media_player.camille_s_speaker
      - type: conditional
        conditions:
          - entity: media_player.mary_s_speaker
            state_not: 'off'
        card:
          type: media-control
          entity: media_player.mary_s_speaker
      - entity: weather.dark_sky
        type: weather-forecast
    icon: ''
    title: Home
  - badges: []
    cards:
      - entity: alarm_control_panel.home_alarm
        states:
          - arm_home
          - arm_away
          - arm_night
        type: alarm-panel
      - entities:
          - entity: binary_sensor.door_sensor_1
          - entity: binary_sensor.door_sensor_2
          - entity: binary_sensor.door_sensor_3
          - entity: binary_sensor.door_sensor_4
        type: glance
      - entities:
          - entity: binary_sensor.motion_office
          - entity: binary_sensor.motion_hallway
          - entity: binary_sensor.motion_living_room
          - entity: binary_sensor.motion_camille_bedroom
          - entity: binary_sensor.motion_master_bedroom
        type: glance
      - entities:
          - entity: input_boolean.door_alert_delay
          - entity: switch.linear_unknown_type_2005_id_0503_switch
        show_header_toggle: false
        type: entities
      - entity: alarm_control_panel.aarlo_lancaster
        states:
          - arm_home
          - arm_away
        type: alarm-panel
      - type: 'custom:aarlo-glance'
        camera: front_door
        name: Front Door
        show:
          - motion
          - sound
          - snapshot
          - battery
          - signal_strength
          - captured
      - type: 'custom:aarlo-glance'
        camera: mary
        name: Mary
        show:
          - motion
          - sound
          - snapshot
          - battery
          - signal_strength
          - captured
      - type: 'custom:aarlo-glance'
        camera: living_room
        name: Living Room
        show:
          - motion
          - sound
          - snapshot
          - battery
          - signal_strength
          - captured
    title: Security
  - badges: []
    cards:
      - entity: media_player.camille_s_speaker
        type: media-control
      - entities:
          - entity: input_select.camille_status
          - entity: input_datetime.alarm_time_camille
          - entity: input_boolean.alarm_disable_camille
        type: entities
      - entities:
          - entity: binary_sensor.motion_camille_bedroom
          - entity: sensor.aeotec_dsb05_multisensor_temperature
          - entity: sensor.aeotec_dsb05_multisensor_relative_humidity
        type: glance
      - entities:
          - entity: light.grandma_s_lamp
          - entity: switch.aeotec_dsc06106_smart_energy_switch_switch_2
          - entity: switch.bedroom_canopy
        title: Lights
        type: entities
    title: Camille
  - cards:
      - entity: media_player.living_room_tv
        type: media-control
      - entity: media_player.living_room_display
        type: media-control
      - entity: media_player.bedroom_speaker
        type: media-control
      - entity: media_player.camille_s_speaker
        type: media-control
      - entity: media_player.mary_s_speaker
        type: media-control
      - entity: media_player.all_rooms
        type: media-control
    title: Media
  - title: Lights
    badges: []
    cards:
      - entities:
          - entity: light.accordion_lamp
          - entity: light.aeotec_zw111_nano_dimmer_level
          - entity: light.aeotec_zw111_nano_dimmer_level_3
          - entity: light.living_room_lamp
        title: Living Room
        type: entities
      - entities:
          - entity: light.aeotec_zw111_nano_dimmer_level_2
        title: "Office"
        type: entities
      - entities:
          - entity: light.grandma_s_lamp
          - entity: switch.aeotec_dsc06106_smart_energy_switch_switch_2
          - entity: switch.bedroom_canopy
        title: "Camille's Room"
        type: entities
      - entities:
          - entity: light.bedroom_lamp
          - entity: light.metal_lamp
        title: Master Bedroom
        type: entities
  - cards:
      - detail: 6
        entity: sensor.temperature_whole_house
        graph: line
        type: sensor
      - detail: 6
        entity: sensor.humidity_whole_house
        graph: line
        type: sensor
      - entities:
          - entity: sensor.linear_wapirz_1_motion_sensor_temperature_3
          - entity: sensor.linear_wapirz_1_motion_sensor_temperature_2
        show_name: false
        title: Living Room
        type: glance
      - entities:
          - entity: sensor.linear_wapirz_1_motion_sensor_temperature
        show_name: false
        title: Mary's Room
        type: glance
      - entities:
          - entity: sensor.aeotec_zw100_multisensor_6_temperature
          - entity: sensor.aeotec_zw100_multisensor_6_relative_humidity
        show_name: false
        title: Master Bedroom
        type: glance
      - entities:
          - entity: sensor.aeotec_dsb05_multisensor_temperature
          - entity: sensor.aeotec_dsb05_multisensor_relative_humidity
        show_name: false
        title: Camille's Bedroom
        type: glance
    title: Climate
