resources:
  - type: module
    url: /local/aarlo-glance.js
title: Home
views:
  - badges: []
    cards:
      - entity: alarm_control_panel.home_alarm
        states:
          - arm_home
          - arm_away
          - arm_night
        type: alarm-panel
      - entities:
          - entity: input_boolean.in_home_services
          - entity: input_boolean.guest_mode
        type: entities
      - detail: 6
        entity: sensor.temperature_whole_house
        graph: line
        type: sensor
      - detail: 6A
        entity: sensor.humidity_whole_house
        graph: line
        type: sensor
      - cards:
          - entities:
              - entity: input_select.michael_status
              - entity: input_select.angela_status
              - entity: input_select.camille_status
            type: glance
          - entities:
              - entity: person.michael
              - entity: person.angela
              - entity: person.camille
            type: history-graph
        type: vertical-stack
      - card:
          entities:
            - entity: switch.linear_unknown_type_2005_id_0503_switch
          type: entities
        conditions:
          - entity: switch.linear_unknown_type_2005_id_0503_switch
            state: 'on'
        type: conditional
      - card:
          entity: media_player.living_room_tv
          type: media-control
        conditions:
          - entity: media_player.living_room_tv
            state_not: 'off'
          - entity: media_player.all_rooms
            state_not: playing
          - entity: media_player.some_things
            state_not: playing
        type: conditional
      - card:
          entity: media_player.living_room_display
          type: media-control
        conditions:
          - entity: media_player.living_room_display
            state_not: 'off'
        type: conditional
      - card:
          entity: media_player.bedroom_speaker
          type: media-control
        conditions:
          - entity: media_player.bedroom_speaker
            state_not: 'off'
          - entity: media_player.all_rooms
            state_not: playing
        type: conditional
      - card:
          entity: media_player.camille_s_speaker
          type: media-control
        conditions:
          - entity: media_player.camille_s_speaker
            state_not: 'off'
          - entity: media_player.all_rooms
            state_not: playing
        type: conditional
      - card:
          entity: media_player.office_speaker
          type: media-control
        conditions:
          - entity: media_player.office_speaker
            state_not: 'off'
        type: conditional
      - card:
          entity: media_player.wooly
          type: media-control
        conditions:
          - entity: media_player.wooly
            state_not: 'off'
          - entity: media_player.all_rooms
            state_not: playing
          - entity: media_player.some_things
            state_not: playing
        type: conditional
      - card:
          entity: media_player.all_rooms
          type: media-control
        conditions:
          - entity: media_player.all_rooms
            state_not: 'off'
        type: conditional
      - card:
          entity: media_player.some_things
          type: media-control
        conditions:
          - entity: media_player.some_things
            state_not: 'off'
        type: conditional
      - entity: weather.dark_sky
        type: weather-forecast
    icon: ''
    title: Home
  - badges: []
    cards:
      - entity: alarm_control_panel.home_alarm
        states:
          - arm_home
          - arm_away
          - arm_night
        type: alarm-panel
      - entities:
          - entity: binary_sensor.door_sensor_1
          - entity: binary_sensor.door_sensor_2
          - entity: binary_sensor.door_sensor_3
          - entity: binary_sensor.door_sensor_4
        type: glance
      - entities:
          - entity: binary_sensor.motion_office
          - entity: binary_sensor.motion_hallway
          - entity: binary_sensor.motion_living_room
          - entity: binary_sensor.motion_camille_bedroom
          - entity: binary_sensor.motion_master_bedroom
        type: glance
      - entities:
          - entity: input_boolean.door_alert_delay
          - entity: switch.linear_unknown_type_2005_id_0503_switch
          - entity: input_boolean.in_home_services
        show_header_toggle: false
        type: entities
      - entity: alarm_control_panel.aarlo_lancaster
        states:
          - arm_home
          - arm_away
        type: alarm-panel
      - camera: front_door
        name: Front Door
        show:
          - motion
          - sound
          - snapshot
          - battery
          - signal_strength
          - captured
        type: 'custom:aarlo-glance'
      - camera: bedroom
        name: Bedroom
        show:
          - motion
          - sound
          - snapshot
          - battery
          - signal_strength
          - captured
        type: 'custom:aarlo-glance'
      - camera: living_room
        name: Living Room
        show:
          - motion
          - sound
          - snapshot
          - battery
          - signal_strength
          - captured
        type: 'custom:aarlo-glance'
      - camera: aquarium
        name: Aquarium
        show:
          - motion
          - sound
          - snapshot
          - battery
          - signal_strength
          - captured
        type: 'custom:aarlo-glance'
    title: Security
  - badges: []
    cards:
      - entity: media_player.camille_s_speaker
        type: media-control
      - entities:
          - entity: input_select.camille_status
          - entity: input_datetime.alarm_time_camille
          - entity: input_boolean.alarm_set_camille
          - entity: automation.wakeup_alarm_repeat_camille
          - entity: automation.lights_on_motion_camille_s_room
        type: entities
      - entities:
          - entity: binary_sensor.motion_camille_bedroom
          - entity: sensor.aeotec_dsb05_multisensor_temperature
          - entity: sensor.aeotec_dsb05_multisensor_relative_humidity
        type: glance
      - entities:
          - entity: light.grandma_s_lamp
          - entity: switch.aeotec_dsc06106_smart_energy_switch_switch_2
          - entity: switch.bedroom_canopy
        title: Lights
        type: entities
    title: Camille
  - cards:
      - entities:
          - entity: switch.zooz_zen06_switch
          - entity: script.tv_time
          - entity: script.radio_time
        type: entities
      - entity: media_player.living_room_tv
        type: media-control
      - entity: media_player.living_room_display
        type: media-control
      - entity: media_player.bedroom_speaker
        type: media-control
      - entity: media_player.camille_s_speaker
        type: media-control
      - entity: media_player.office_speaker
        type: media-control
      - entity: media_player.wooly
        type: media-control
      - entity: media_player.all_rooms
        type: media-control
      - entity: media_player.some_things
        type: media-control
    title: Media
  - badges: []
    cards:
      - entities:
          - entity: light.accordion_lamp
          - entity: light.aeotec_zw111_nano_dimmer_level
          - entity: light.aeotec_zw111_nano_dimmer_level_3
          - entity: light.living_room_lamp
        title: Living Room
        type: entities
      - entities:
          - entity: light.aeotec_zw111_nano_dimmer_level_2
        title: Office
        type: entities
      - entities:
          - entity: light.grandma_s_lamp
          - entity: switch.aeotec_dsc06106_smart_energy_switch_switch_2
          - entity: switch.bedroom_canopy
        title: Camille's Room
        type: entities
      - entities:
          - entity: light.bedroom_lamp
          - entity: light.metal_lamp
        title: Master Bedroom
        type: entities
    title: Lights
  - cards:
      - detail: 6
        entity: sensor.temperature_whole_house
        graph: line
        type: sensor
      - detail: 6
        entity: sensor.humidity_whole_house
        graph: line
        type: sensor
      - entities:
          - entity: sensor.linear_wapirz_1_motion_sensor_temperature_3
          - entity: sensor.linear_wapirz_1_motion_sensor_temperature_2
        show_name: false
        title: Living Room
        type: glance
      - entities:
          - entity: sensor.linear_wapirz_1_motion_sensor_temperature
        show_name: false
        title: Office
        type: glance
      - entities:
          - entity: sensor.aeotec_zw100_multisensor_6_temperature
          - entity: sensor.aeotec_zw100_multisensor_6_relative_humidity
        show_name: false
        title: Master Bedroom
        type: glance
      - entities:
          - entity: sensor.aeotec_dsb05_multisensor_temperature
          - entity: sensor.aeotec_dsb05_multisensor_relative_humidity
        show_name: false
        title: Camille's Bedroom
        type: glance
    title: Climate
  - badges: []
    cards:
      - entities:
          - entity: sensor.aarlo_battery_level_aquarium
          - entity: sensor.aarlo_battery_level_front_door
          - entity: sensor.aarlo_battery_level_living_room
          - entity: sensor.aarlo_battery_level_bedroom
        show_header_toggle: false
        title: Arlo
        type: entities
      - entities:
          - entity: sensor.aeotec_dsb05_multisensor_battery_level
          - entity: sensor.aeotec_zw100_multisensor_6_battery_level
          - entity: sensor.linear_wadwaz_1_door_window_sensor_2_battery_level
          - entity: sensor.linear_wadwaz_1_door_window_sensor_3_battery_level
          - entity: sensor.linear_wadwaz_1_door_window_sensor_4_battery_level
          - entity: sensor.linear_wadwaz_1_door_window_sensor_battery_level
          - entity: sensor.linear_wapirz_1_motion_sensor_2_battery_level
          - entity: sensor.linear_wapirz_1_motion_sensor_3_battery_level
          - entity: sensor.linear_wapirz_1_motion_sensor_battery_level
        show_header_toggle: false
        title: Sensors
        type: entities
      - entities:
          - entity: sensor.angela_pfammatters_iphone_battery_level
          - entity: sensor.ergisch_battery_level
        show_header_toggle: false
        title: Phones
        type: entities
      - entities:
          - entity: sensor.date
          - entity: sensor.time
          - entity: sensor.weekday
          - entity: binary_sensor.workday_sensor
        show_header_toggle: false
        type: entities
    icon: ''
    title: System
