group:
  lights_whole_house:
    name: All lights in the house
    entities:
      - light.metal_lamp
      - light.entry_light
      - light.bedroom_lamp
      # Camille's closet light
      - light.ge_appliances_zll_light_1b550600_level_on_off
      - light.grandma_s_lamp
      - light.living_room_lamp
      # Master closet light
      - light.ikea_of_sweden_tradfri_bulb_e26_ws_opal_1000lm_62b607fe_level_light_color_on_off
      # Laundry closet light
      - light.ikea_of_sweden_tradfri_bulb_e26_ws_opal_1000lm_8c905bfe_level_light_color_on_off
      # Entry closet light
      - light.ikea_of_sweden_tradfri_bulb_e26_ws_opal_1000lm_50db9afe_level_light_color_on_off
      # Bedroom lamp left
      - light.ikea_of_sweden_tradfri_bulb_e26_ws_opal_1000lm_989e43fe_level_light_color_on_off
      # Accordion Lamp
      - light.ikea_of_sweden_tradfri_bulb_e26_ws_opal_1000lm_166ca8fe_level_light_color_on_off

  lights_away:
    name: All lights when away
    entities:
      - light.metal_lamp
      - light.entry_light
      - light.bedroom_lamp
      # Camille's closet light
      - light.ge_appliances_zll_light_1b550600_level_on_off
      - light.living_room_lamp
      # Master closet light
      - light.ikea_of_sweden_tradfri_bulb_e26_ws_opal_1000lm_62b607fe_level_light_color_on_off
      # Laundry closet light
      - light.ikea_of_sweden_tradfri_bulb_e26_ws_opal_1000lm_8c905bfe_level_light_color_on_off
      # Entry closet light
      - light.ikea_of_sweden_tradfri_bulb_e26_ws_opal_1000lm_50db9afe_level_light_color_on_off
      # Bedroom lamp left
      - light.ikea_of_sweden_tradfri_bulb_e26_ws_opal_1000lm_989e43fe_level_light_color_on_off
      # Accordion Lamp
      - light.ikea_of_sweden_tradfri_bulb_e26_ws_opal_1000lm_166ca8fe_level_light_color_on_off

  lights_switches_for_flashing:
    name: All lights that are good for flashing
    entities:
      # Bedroom lamp left
      - light.ikea_of_sweden_tradfri_bulb_e26_ws_opal_1000lm_989e43fe_level_light_color_on_off
      # Accordion Lamp
      - light.ikea_of_sweden_tradfri_bulb_e26_ws_opal_1000lm_166ca8fe_level_light_color_on_off
      # Camille's closet light
      - light.ge_appliances_zll_light_1b550600_level_on_off
      - switch.bedroom_canopy
      # Nani' lamp
      - switch.aeon_labs_zw096_smart_switch_6_switch
      # Living room lamp lefty
      - switch.aeon_labs_zw096_smart_switch_6_switch_2
      - light.living_room_lamp
      - light.metal_lamp
      - light.entry_light
      - light.bedroom_lamp

  switches_whole_house:
    name: All switches in the house
    entities:
      - switch.zooz_zen06_switch
      - switch.bedroom_canopy
      - switch.zooz_zen20_v2_0_power_strip_switch
      - switch.zooz_zen20_v2_0_power_strip_switch_2
      - switch.zooz_zen20_v2_0_power_strip_switch_3
      - switch.zooz_zen20_v2_0_power_strip_switch_4
      - switch.zooz_zen20_v2_0_power_strip_switch_5
      - switch.zooz_zen20_v2_0_power_strip_switch_6
      - switch.aeon_labs_zw096_smart_switch_6_switch
      - switch.aeon_labs_zw096_smart_switch_6_switch_2

  media_whole_house:
    name: All media in the house
    entities:
      - media_player.bedroom_speaker
      - media_player.camille_s_speaker
      - media_player.living_room_display
      - media_player.living_room_tv
      - media_player.office_speaker

automation:
  - alias: "Alarm night turn off everything"
    trigger:
      - platform: state
        entity_id: alarm_control_panel.home_alarm
        to: "armed_night"
    action:
      - service: homeassistant.turn_off
        data:
          entity_id:
            - group.lights_whole_house
            - group.switches_whole_house
      - service: media_player.media_pause
        data:
          entity_id:
            - media_player.bedroom_speaker
            - media_player.living_room_tv
            - media_player.living_room_display

  - alias: "Alarm away turn off everything"
    trigger:
      - platform: state
        entity_id: alarm_control_panel.home_alarm
        to: "armed_away"
    action:
      - service: script.turn_everything_off_away

  - alias: "No motion late at night"
    trigger:
      - platform: state
        entity_id: group.motion_sensors
        to: "off"
        for:
          minutes: 45
      - platform: time
        at: "01:05:00"
    condition:
      - condition: time
        after: "01:00:00"
        before: "05:00:00"
      - condition: state
        entity_id: alarm_control_panel.home_alarm
        state: "disarmed"
      - condition: state
        entity_id: input_boolean.guest_mode
        state: "off"
      - condition: template
        value_template: >-
          {{ as_timestamp(states.sensor.time.last_changed) - as_timestamp(states.group.motion_sensors.last_changed) > (44*60)
             and states("group.motion_sensors") == "off" }}
    action:
      - service: alarm_control_panel.alarm_arm_night
        entity_id: alarm_control_panel.home_alarm

  - alias: "Hall light alarm pending"
    trigger:
      - platform: state
        entity_id: alarm_control_panel.home_alarm
        to: "pending"
    condition:
      - condition: state
        entity_id: light.aeon_labs_zw111_nano_dimmer_level_3
        state: "off"
    action:
      - service: homeassistant.turn_on
        entity_id:
          - light.aeon_labs_zw111_nano_dimmer_level_3
          - light.aeon_labs_zw111_nano_dimmer_level_4

  - alias: "Master Closet Door Open Turn On Light"
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.door_sensor_4
    action:
      - entity_id: light.ikea_of_sweden_tradfri_bulb_e26_ws_opal_1000lm_50db9afe_level_light_color_on_off
        service_template: >-
          {% if trigger.to_state.state == "on" %}
          homeassistant.turn_on
          {% else %}
          homeassistant.turn_off
          {% endif %}

  - alias: "Whole House Pandemic Light Party at 8pm"
    trigger:
      - platform: time
        at: '20:00:00'
    action:
      - service: script.whole_house_lights_pandemic_flash


script:
  turn_everything_off:
    alias: "Turn everything off"
    sequence:
      - service: homeassistant.turn_off
        data:
          entity_id:
            - group.lights_whole_house
            - group.switches_whole_house
      - service: media_player.media_pause
        data:
          entity_id:
            - group.media_whole_house

  turn_off_media:
    alias: "Turn off all media"
    sequence:
      - service: media_player.media_pause
        data:
          entity_id:
            - group.media_whole_house

  turn_everything_off_away:
    alias: "Turn everything off away"
    sequence:
      - service: homeassistant.turn_off
        data:
          entity_id:
            - group.lights_away
            - group.switches_whole_house
      - service: media_player.media_pause
        data:
          entity_id:
            - group.media_whole_house
  get_dark:
    alias: "Get dark"
    sequence:
      - service: homeassistant.turn_off
        data:
          entity_id:
            - light.ge_appliances_zll_light_1b550600_level_on_off
            - light.living_room_lamp
            - switch.aeon_labs_zw096_smart_switch_6_switch
            - switch.aeon_labs_zw096_smart_switch_6_switch_2

  whole_house_lights_pandemic_flash:
    alias: "Flash all lights for the pandemic party"
    sequence:
      - service: homeassistant.turn_off
        data:
          entity_id: switch.jasco_products_14284_outdoor_smart_switch_switch
      - service: homeassistant.toggle
        data:
          entity_id: group.lights_switches_for_flashing
      - delay: "00:00:02"
      - service: homeassistant.toggle
        data:
          entity_id: group.lights_switches_for_flashing
      - delay: "00:00:02"
      - service: homeassistant.toggle
        data:
          entity_id: group.lights_switches_for_flashing
      - delay: "00:00:02"
      - service: homeassistant.toggle
        data:
          entity_id: group.lights_switches_for_flashing
      - delay: "00:00:02"
      - service: homeassistant.toggle
        data:
          entity_id: group.lights_switches_for_flashing
      - delay: "00:00:02"
      - service: homeassistant.toggle
        data:
          entity_id: group.lights_switches_for_flashing
      - delay: "00:00:02"
      - service: homeassistant.toggle
        data:
          entity_id: group.lights_switches_for_flashing
      - delay: "00:00:02"
      - service: homeassistant.toggle
        data:
          entity_id: group.lights_switches_for_flashing
      - delay: "00:10:00"
      - service: homeassistant.turn_off
        data:
          entity_id: switch.jasco_products_14284_outdoor_smart_switch_switch
