automation:
  - alias: Aquarium Light On
    trigger:
      - platform: time
        at: '07:00:00'
      - platform: time
        at: '16:00:00'
    action:
      - service: homeassistant.turn_on
        entity_id:
          - switch.aeotec_dsc06106_smart_energy_switch_switch


  - alias: Aquarium Light Off
    trigger:
      - platform: time
        at: '13:00:00'
      - platform: time
        at: '21:00:00'
    action:
      - service: homeassistant.turn_off
        entity_id:
          - switch.aeotec_dsc06106_smart_energy_switch_switch
