input_select:
  angela_status:
    name: "Angela"
    options:
      - Home
      - Work
      - Away
      - Asleep
    icon: mdi:account
    # icon: >-
    #   {% if states("input_select.angela_status") == "Home" %}
    #   mdi:home
    #   {% elif states("input_select.angela_status") == "Work" %}
    #   mdi:account-badge-horizontal
    #   {% elif states("input_select.angela_status") == "Asleep" %}
    #   mdi:hotel
    #   {% else %}
    #   mdi:logout
    #   {% endif %}

automation:
  - alias: Set status for Angela asleep
    trigger:
      - platform: state
        entity_id: binary_sensor.sleepnumber_michael_angela_is_in_bed
        to: "on"
        for:
          minutes: 5
      - platform: numeric_state
        entity_id: sensor.aeotec_zw100_multisensor_6_luminance
        below: 4
    condition:
      - condition: numeric_state
        entity_id: sensor.aeotec_zw100_multisensor_6_luminance
        below: 4
      - condition: state
        entity_id: binary_sensor.sleepnumber_michael_angela_is_in_bed
        state: "on"
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.angela_status
          option: "Asleep"

  - alias: Set status for Angela awake
    trigger:
      - platform: state
        entity_id: binary_sensor.sleepnumber_michael_angela_is_in_bed
        to: "off"
        from: "on"
    condition:
      - condition: state
        entity_id: input_select.angela_status
        state: "Asleep"
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.angela_status
          option: "Home"
