input_select:
  daisy_status:
    name: "Daisy's Status"
    options:
      - Home
      - Away
      - Asleep

input_boolean:
  daisy_walked:
    name: "Daisy Walked"
  daisy_outside:
    name: "Daisy might be outside"

input_datetime:
  daisy_log_updated:
    name: "Daisy's Log Updated"
    icon: mdi:dog
    has_date: true
    has_time: true

automation:
  - alias: "Daisy mark awake on motion"
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_camille_bedroom
        from: "off"
        to: "on"
    condition:
      - condition: state
        entity_id: input_select.daisy_status
        state: "Asleep"
    action:
      - service: homeassistant.turn_off
        data:
          entity_id:
            - input_boolean.daisy_walked
      - service: input_select.select_option
        data:
          entity_id: input_select.daisy_status
          option: "Home"

  # - alias: Daisy awake
  #   trigger:
  #     - platform: state
  #       entity_id: input_select.camille_status
  #       from: "Asleep"
  #       to: "Home"
  #   condition:
  #     - condition: template
  #       value_template: >-
  #         {{ states.input_select.daisy_state != "Away" }}
  #   action:
  #     - service: homeassistant.turn_off
  #       data:
  #         entity_id:
  #           - input_boolean.daisy_walked
  #     - service: input_select.select_option
  #       data:
  #         entity_id: input_select.daisy_status
  #         option: "Home"

  - alias: Daisy walk first thing
    trigger:
      - platform: time_pattern
        minutes: "/1"
    condition:
      - condition: state
        entity_id: input_boolean.daisy_walked
        state: "off"
      - condition: template
        value_template: >-
          {{ states.input_select.daisy_state != "Away" }}
      - condition: template
        value_template: >-
          {{ ((as_timestamp(utcnow()) - as_timestamp(states.input_boolean.daisy_walked.last_changed)) / 60) > 1 and
             (((as_timestamp(utcnow()) - as_timestamp(states.input_boolean.daisy_walked.last_changed))/60)|int) % 5 == 0 }}
    action:
      - service: tts.google_translate_say
        data:
          entity_id:
            - media_player.living_room_display
            - media_player.camille_s_speaker
          message: "Take Daisy outside"
      - service: notify.mobile_app_ergisch
        data:
          title: "Daisy Alert"
          message: "Daisy needs to go!"

  - alias: Daisy time to feed
    trigger: 
      - platform: time
        at: "17:00:00"
    condition:
      - condition: template
        value_template: >-
          {{ states.input_select.daisy_state != "Away" }}
    action:
      - service: tts.google_translate_say
        data:
          entity_id:
            - media_player.living_room_display
            - media_player.camille_s_speaker
          message: "Time to feed Daisy"
      - service: notify.mobile_app_ergisch
        data:
          title: "Time to feed Daisy"
          message: "Click to fill log"
          data:
            url: "https://docs.google.com/forms/d/e/1FAIpQLSdc1HbpBndlpDK7QokvjB7k6AlDmGeQFAsS1K6cpBP2d-dHwg/viewform?usp=sf_link"

  - alias: Daisy time to train
    trigger: 
      - platform: time
        at: "15:00:00"
    condition:
      - condition: template
        value_template: >-
          {{ states.input_select.daisy_state != "Away" }}
    action:
      - service: tts.google_translate_say
        data:
          entity_id:
            - media_player.living_room_display
            - media_player.camille_s_speaker
          message: "Time to train Daisy"
      - service: notify.mobile_app_ergisch
        data:
          title: "Time to feed Daisy"
          message: "Click to fill log"
          data:
            url: "https://docs.google.com/forms/d/e/1FAIpQLSdc1HbpBndlpDK7QokvjB7k6AlDmGeQFAsS1K6cpBP2d-dHwg/viewform?usp=sf_link"

  - alias: Daisy mark walked on door open
    trigger:
      - platform: state
        entity_id: binary_sensor.door_sensor_2
        from: "off"
        to: "on"
    condition:
      - condition: template
        value_template: >-
          {{ states.input_select.daisy_state != "Away" }}
      - condition: template
        value_template: >-
          {{ states.input_select.daisy_state != "Away" }}
    action:
      - service: homeassistant.turn_on
        entity_id: input_boolean.daisy_walked
      - service: notify.mobile_app_michaels_ipad
        data:
          title: "Daisy Alert"
          message: "Front door opened. Fill out the log."

  - alias: Daisy mark outside
    trigger:
      - platform: state
        entity_id: binary_sensor.door_sensor_2
        from: "off"
        to: "on"
    condition:
      - condition: state
        entity_id: input_select.daisy_status
        state: "Home"
      - condition: state
        entity_id: input_boolean.daisy_outside
        state: "off"
    action:
      - service: homeassistant.turn_on
        data:
          entity_id: input_boolean.daisy_outside 

  - alias: Daisy mark inside by time
    trigger:
      - platform: state
        entity_id: input_boolean.daisy_outside
        to: "on"
        for: 15
    condition:
      - condition: state
        entity_id: input_select.daisy_status
        state: "Home"
      - condition: state
        entity_id: input_boolean.daisy_outside
        state: "on"
    action:
      - service: homeassistant.turn_off
        data:
          entity_id: input_boolean.daisy_outside 

  - alias: Daisy mark inside by door
    trigger:
      - platform: state
        entity_id: binary_sensor.door_sensor_2
        from: "off"
        to: "on"
    condition:
      - condition: state
        entity_id: input_select.daisy_status
        state: "Home"
      - condition: state
        entity_id: input_boolean.daisy_outside
        state: "on"
      - condition: state
        entity_id: binary_sensor.door_sensor_2
        state: "off"
        for:
          minutes: 2
    action:
      - service: homeassistant.turn_off
        data:
          entity_id: input_boolean.daisy_outside 
      - service: notify.mobile_app_michaels_ipad
        data:
          title: "Daisy Alert"
          message: "Click to fill log"
      - service_template: >-
          {% if states.input_select.michael_status == "Home" %}
          notify.mobile_app_ergisch
          data:
            title: "Daisy Alert"
            message: "Front door opened. Click to fill log"
            data:
              url: "https://docs.google.com/forms/d/e/1FAIpQLSdc1HbpBndlpDK7QokvjB7k6AlDmGeQFAsS1K6cpBP2d-dHwg/viewform?usp=sf_link"
          {% else %}
          script.placeholder
          {% endif %}

  # - alias: Daisy log on door open Michael
  #   trigger:
  #     - platform: state
  #       entity_id: binary_sensor.door_sensor_2
  #       from: "off"
  #       to: "on"
  #   condition:
  #     - condition: state
  #       entity_id: input_select.michael_status
  #       state: "Home"
  #   action:
  #     - service: notify.mobile_app_ergisch
  #       data:
  #         title: "Daisy Alert"
  #         message: "Front door opened. Click to fill log"
  #         data:
  #           url: "https://docs.google.com/forms/d/e/1FAIpQLSdc1HbpBndlpDK7QokvjB7k6AlDmGeQFAsS1K6cpBP2d-dHwg/viewform?usp=sf_link"

  - alias: "Daisy Minimote Camille Hold"
    trigger:
      - platform: state
        entity_id:
          - input_boolean.minimote_camille_2
          - input_boolean.minimote_camille_4
          - input_boolean.minimote_camille_6
          - input_boolean.minimote_camille_8
    action:
      - service: homeassistant.toggle
        data_template:
          entity_id: >-
            {% if is_state("input_select.daisy_status", "Asleep") %}
              {% set runScript = "script.daisy_goodmorning" %}
            {% elif is_state("input_select.daisy_status", "Home") %}
              {% set runScript = "script.daisy_goodnight" %}
            {% else %}
              {% set runScript = "script.placeholder" %}
            {% endif %}
            {{ runScript }}

  - alias: "Daisy log time updater"
    trigger:
      - platform: webhook
        webhook_id: d02bf9a5-7dab-4e9f-9e1b-240b6edde23e 
    action:
      - service: input_datetime.set_datetime
        data_template:
          entity_id: input_datetime.date_and_time
          date: >-
            {{ now().timestamp() | timestamp_custom("%Y-%m-%d", true) }}
          time: >-
            {{ now().timestamp() | timestamp_custom("%H:%M:%S", true) }}
script:
  daisy_goodmorning:
    alias: Good Night Daisy
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.daisy_status
          option: "Home"

  daisy_goodnight:
    alias: Good Night Daisy
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.daisy_status
          option: "Asleep"
