input_select:
  angela_status:
    name: "Angela"
    options:
      - Home
      - Work
      - Away
      - Asleep
    icon: mdi:account
    # icon: >-
    #   {% if states("input_select.angela_status") == "Home" %}
    #   mdi:home
    #   {% elif states("input_select.angela_status") == "Work" %}
    #   mdi:account-badge-horizontal
    #   {% elif states("input_select.angela_status") == "Asleep" %}
    #   mdi:hotel
    #   {% else %}
    #   mdi:logout
    #   {% endif %}

automation:
  - alias: Set status for Angela
    trigger:
      - platform: state
        entity_id: person.angela
    condition:
      - condition: template
        value_template: "{{ trigger.to_state.state != trigger.from_state.state }}"
    action:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.angela_status
          option: >-
              {% if states("person.angela") == "home" %}
              Home
              {% elif states("person.angela") == "Work Angela" %}
              Work
              {% else %}
              Away
              {% endif %}

  - alias: Set status for Angela asleep
    trigger:
      - platform: state
        entity_id: binary_sensor.sleepnumber_michael_angela_is_in_bed
        for:
          minutes: 2
    condition:
      - condition: state
        entity_id: sensor.aeotec_zw100_multisensor_6_luminance
        below: 4
      - condition: state
        entity_id: person.angela
        state: "home"
