input_select:
  daisy_status:
    name: "Daisy's Status"
    options:
      - Home
      - Away
      - Asleep

input_boolean:
  daisy_walked:
    name: "Daisy Walked"

automation:
  - alias: "Daisy mark awake on motion"
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_camille_bedroom
        from: "off"
        to: "on"
    condition:
      - condition: state
        entity_id: input_select.daisy_status
        state: "Asleep"
    action:
      - service: homeassistant.turn_off
        data:
          entity_id:
            - input_boolean.daisy_walked
      - service: input_select.select_option
        data:
          entity_id: input_select.daisy_status
          option: "Home"
  # - alias: Daisy awake
  #   trigger:
  #     - platform: state
  #       entity_id: input_select.camille_status
  #       from: "Asleep"
  #       to: "Home"
  #   condition:
  #     - condition: template
  #       value_template: >-
  #         {{ states.input_select.daisy_state != "Away" }}
  #   action:
  #     - service: homeassistant.turn_off
  #       data:
  #         entity_id:
  #           - input_boolean.daisy_walked
  #     - service: input_select.select_option
  #       data:
  #         entity_id: input_select.daisy_status
  #         option: "Home"

  - alias: Daisy walk first thing
    trigger:
      - platform: time_pattern
        minutes: "/1"
    condition:
      - condition: state
        entity_id: input_boolean.daisy_walked
        state: "off"
      - condition: template
        value_template: >-
          {{ states.input_select.daisy_state != "Away" }}
      - condition: template
        value_template: >-
          {{ ((as_timestamp(utcnow()) - as_timestamp(states.input_boolean.daisy_walked.last_changed)) / 60) > 1 and
             (((as_timestamp(utcnow()) - as_timestamp(states.input_boolean.daisy_walked.last_changed))/60)|int) % 5 == 0 }}
    action:
      - service: tts.google_translate_say
        data:
          entity_id:
            - media_player.living_room_display
            - media_player.camille_s_speaker
          message: "Take Daisy outside"
      - service: notify.mobile_app_ergisch
        data:
          title: "Daisy Alert"
          message: "Daisy needs to go!"

  - alias: Daisy time to feed
    trigger: 
      - platform: time
        at: "17:00:00"
    condition:
      - condition: template
        value_template: >-
          {{ states.input_select.daisy_state != "Away" }}
    action:
      - service: tts.google_translate_say
        data:
          entity_id:
            - media_player.living_room_display
            - media_player.camille_s_speaker
          message: "Time to feed Daisy"
      - service: notify.mobile_app_ergisch
        data:
          title: "Time to feed Daisy"
          message: "Click to fill log"
          data:
            url: "https://docs.google.com/forms/d/e/1FAIpQLSdc1HbpBndlpDK7QokvjB7k6AlDmGeQFAsS1K6cpBP2d-dHwg/viewform?usp=sf_link"

  - alias: Daisy time to train
    trigger: 
      - platform: time
        at: "15:00:00"
    condition:
      - condition: template
        value_template: >-
          {{ states.input_select.daisy_state != "Away" }}
    action:
      - service: tts.google_translate_say
        data:
          entity_id:
            - media_player.living_room_display
            - media_player.camille_s_speaker
          message: "Time to train Daisy"
      - service: notify.mobile_app_ergisch
        data:
          title: "Time to feed Daisy"
          message: "Click to fill log"
          data:
            url: "https://docs.google.com/forms/d/e/1FAIpQLSdc1HbpBndlpDK7QokvjB7k6AlDmGeQFAsS1K6cpBP2d-dHwg/viewform?usp=sf_link"

  - alias: Daisy mark walked on door open
    trigger:
      - platform: state
        entity_id: binary_sensor.door_sensor_2
        from: "off"
        to: "on"
    condition:
      - condition: template
        value_template: >-
          {{ states.input_select.daisy_state != "Away" }}
    action:
      - service: homeassistant.turn_on
        entity_id: input_boolean.daisy_walked
      - service: notify.mobile_app_michaels_ipad
        data:
          title: "Daisy Alert"
          message: "Front door opened. Fill out the log."

  - alias: Daisy log on door open Michael
    trigger:
      - platform: state
        entity_id: binary_sensor.door_sensor_2
        from: "off"
        to: "on"
    condition:
      - condition: state
        entity_id: input_select.michael_status
        state: "Home"
    action:
      - service: notify.mobile_app_ergisch
        data:
          title: "Daisy Alert"
          message: "Front door opened. Click to fill log"
          data:
            url: "https://docs.google.com/forms/d/e/1FAIpQLSdc1HbpBndlpDK7QokvjB7k6AlDmGeQFAsS1K6cpBP2d-dHwg/viewform?usp=sf_link"

  - alias: "Daisy Minimote Camille Hold"
    trigger:
      - platform: state
        entity_id:
          - input_boolean.minimote_camille_2
          - input_boolean.minimote_camille_4
          - input_boolean.minimote_camille_6
          - input_boolean.minimote_camille_8
    action:
      - service: homeassistant.toggle
        data_template:
          entity_id: >-
            {% if is_state("input_select.daisy_status", "Asleep") %}
              {% set runScript = "script.daisy_goodmorning" %}
            {% elseif is_state("input_select.daisy_status", "Home") %}
              {% set runScript = "script.daisy_goodnight" %}
            {% else %}
              {% set runScript = "script.placeholder" %}
            {% endif %}
            {{ runScript }}
script:
  daisy_goodmorning:
    alias: Good Night Daisy
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.daisy_status
          option: "Home"

  daisy_goodnight:
    alias: Good Night Daisy
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.daisy_status
          option: "Asleep"
