group:
  lights_living_room:
    name: Living Room Lights
    entities:
      - light.ge_appliances_zll_light_15cd1400_level_on_off
      - light.ikea_of_sweden_tradfri_bulb_e26_ws_opal_1000lm_989e43fe_level_light_color_on_off
  switches_living_room:
    name: Living Room Switches
    entities:
      - switch.aeon_labs_zw096_smart_switch_6_switch_2
  lights_switches_living_room:
    name: Living Room Switches
    entities:
      - light.ge_appliances_zll_light_15cd1400_level_on_off
      - light.ikea_of_sweden_tradfri_bulb_e26_ws_opal_1000lm_989e43fe_level_light_color_on_off
      - switch.aeon_labs_zw096_smart_switch_6_switch_2

automation:
  - alias: Wakeup Living Room
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.motion_living_room
          - binary_sensor.motion_hallway
        to: 'on'
    condition:
      - condition: time
        after: '05:00:00'
        before: '23:30:00'
    action:
      - service: homeassistant.turn_on
        entity_id: script.goodmorning_living_room

  - alias: Wakeup Living Room Setup
    trigger:
      - platform: state
        entity_id: alarm_control_panel.home_alarm
        to: "disarmed"
    action:
      - service: homeassistant.turn_on
        entity_id: automation.wakeup_living_room

script:
  tv_time:
    alias: TV Time
    sequence:
      - service: switch.turn_on
        data:
          entity_id: switch.zooz_zen06_switch
      - service: media_player.volume_set
        data:
          entity_id: media_player.living_room_tv
          volume_level: 0.8

  radio_time:
    alias: Radio Time
    sequence:
      - service: switch.turn_on
        data:
          entity_id: switch.zooz_zen06_switch
      - service: media_player.volume_set
        data:
          entity_id: media_player.living_room_tv
          volume_level: 0.3

  get_mellowed:
    alias: Get Mellowed
    sequence:
      - service: light.turn_on
        data:
          entity_id:
            - light.ge_appliances_zll_light_15cd1400_level_on_off
            - light.ikea_of_sweden_tradfri_bulb_e26_ws_opal_1000lm_989e43fe_level_light_color_on_off
          brightness: 10
      - service: homeassistant.turn_off
        data:
          entity_id:
            - switch.aeon_labs_zw096_smart_switch_6_switch_2

  goodmorning_living_room:
    alias: Goodmorning Living Room
    sequence:
      - service: media_player.volume_set
        data:
          entity_id: media_player.living_room_tv
          volume_level: 0.3
      - service: light.turn_on
        data:
          entity_id:
            # - light.aeotec_zw111_nano_dimmer_level
            # - light.aeotec_zw111_nano_dimmer_level_3
            - light.living_room_lamp
            # - light.aeon_labs_zw111_nano_dimmer_level_3
            # - light.aeon_labs_zw111_nano_dimmer_level_4
          brightness: 255
      - service: switch.turn_on
        data:
          entity_id:
            - switch.zooz_zen06_switch
            # - switch.bedroom_canopy
            - switch.aeon_labs_zw096_smart_switch_6_switch
            - switch.aeon_labs_zw096_smart_switch_6_switch_2
      - service: homeassistant.turn_off
        data:
          entity_id:
            - automation.wakeup_living_room
