group:
  lights_whole_house:
    name: All lights in the house
    view: false
    entities:
      - light.metal_lamp
      - light.entry_light
      - light.bedroom_lamp
      - light.accordion_lamp
      - light.grandma_s_lamp
      - light.living_room_lamp
      - light.aeotec_zw111_nano_dimmer_level
      - light.aeotec_zw111_nano_dimmer_level_2
      - light.aeotec_zw111_nano_dimmer_level_3
  switches_whole_house:
    name: All switches in the house
    view: false
    entities:
      - switch.zooz_zen06_switch
      - switch.bedroom_canopy
      - switch.aeotec_dsc06106_smart_energy_switch_switch_2
  media_whole_house:
    name: All media in the house
    view: false
    entities:
      - media_player.bedroom_speaker
      - media_player.camille_s_speaker
      - media_player.living_room_display
      - media_player.living_room_tv
      - media_player.office_speaker

automation:
  - alias: "Alarm night turn off everything"
    trigger:
      - platform: state
        entity_id: alarm_control_panel.home_alarm
        to: "armed_night"
    action:
      - service: homeassistant.turn_off
        data:
          entity_id:
            - group.lights_whole_house
            - group.switches_whole_house
      - service: media_player.media_pause
        data:
          entity_id:
            - media_player.bedroom_speaker
            - media_player.living_room_tv
            - media_player.living_room_display

  - alias: "Alarm away turn off everything"
    trigger:
      - platform: state
        entity_id: alarm_control_panel.home_alarm
        to: "armed_away"
    action:
      - service: script.turn_everything_off

  - alias: "No motion late at night"
    trigger:
      - platform: state
        entity_id: group.motion_sensors
        to: "off"
        for:
          minutes: 45
      - platform: time
        at: "01:05:00"
    condition:
      - condition: time
        after: "01:00:00"
        before: "05:00:00"
      - condition: state
        entity_id: alarm_control_panel.home_alarm
        state: "disarmed"
      - condition: template
        value_template: >-
          {{ as_timestamp(states.sensor.time.last_changed) - as_timestamp(states.group.motion_sensors.last_changed) > (44*60)
             and states("group.motion_sensors") == "off" }}
    action:
      - service: alarm_control_panel.alarm_arm_home
        entity_id: alarm_control_panel.home_alarm


script:
  turn_everything_off:
    alias: "Turn everything off"
    sequence:
      - service: homeassistant.turn_off
        data:
          entity_id:
            - group.lights_whole_house
            - group.switches_whole_house
      - service: media_player.media_pause
        data:
          entity_id:
            - group.media_whole_house

  turn_off_media:
    alias: "Turn off all media"
    sequence:
      - service: media_player.media_pause
        data:
          entity_id:
            - group.media_whole_house

  get_dark:
    alias: "Get dark"
    sequence:
      - service: homeassistant.turn_off
        data:
          entity_id:
            - light.accordion_lamp
            - light.living_room_lamp
            - light.aeotec_zw111_nano_dimmer_level
            - light.aeotec_zw111_nano_dimmer_level_3
