input_select:
  mary_status:
    name: "Mary's Status"
    options:
      - Home
      - Away
      - Asleep

automation:
  - alias: Goodnight Mary
    trigger:
      - platform: state
        entity_id: switch.aeotec_zw111_nano_dimmer_switch_2
    condition:
      - condition: time
        after: '18:00:00'
        before: '22:00:00'
      - condition: state
        entity_id: input_select.mary_status
        state: "Home"
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.mary_status
          option: "Asleep"

  - alias: Goodmorning Mary
    trigger:
      - platform: state
        entity_id: switch.aeotec_zw111_nano_dimmer_switch_2
    condition:
      - condition: time
        after: '06:30:00'
        before: '11:00:00'
      - condition: state
        entity_id: input_select.mary_status
        state: "Asleep"
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.mary_status
          option: "Home"
