automation:
  - alias: Office all lights on with switch
    trigger:
      - platform: state
        entity_id:
          - switch.aeotec_zw111_nano_dimmer_switch_2
    condition:
      - condition: template
        value_template: >-
          {{ (states.switch.aeotec_zw111_nano_dimmer_switch_2.last_changed | as_timestamp) <
             (states.light.aeotec_zw111_nano_dimmer_level_2.last_changed | as_timestamp)}}

    action:
      - entity_id: switch.aeon_labs_zw096_smart_switch_6_switch
        service_template: >-
          {% if trigger.to_state.state == "on" %}
          homeassistant.turn_on
          {% else %}
          homeassistant.turn_off
          {% endif %}
