homekit:
  filter:
    include_domains:
      - alarm_control_panel
      - light
      - media_player
    include_entities:
      - script.tv_time
      - script.radio_time
      - script.get_mellowed
      - script.get_dark
      - script.goodnight_camille
      - switch.bedroom_canopy
      - switch.zooz_zen06_switch
      - switch.aeon_labs_zw096_smart_switch_6_switch
      - switch.aeotec_dsc06106_smart_energy_switch_switch_2
    exclude_entities:
      - light.ge_link_bulb
      - light.entry_light
  auto_start: false

automation:
  - alias: Homekit start on zwave start
    trigger:
      - platform: state
        entity_id: input_boolean.z_wave_network_ready
    action:
      - service: homekit.start
