sensor:
  - platform: template
    sensors:
      humidity_whole_house:
        friendly_name: Whole House Humidity
        unit_of_measurement: '%'
        value_template: >-
          {% if states("input_boolean.z_wave_network_ready") == "on" %}
            {{ ((states("sensor.aeotec_dsb05_multisensor_relative_humidity")|float +
              states("sensor.aeotec_zw100_multisensor_6_relative_humidity")|float)/2)|round(1) }}
          {% else %}
            {{ states("sensor.humidity_whole_house")}}
          {% endif %}
