group:
  temperature_sensors:
    name: Temperature Sensors
    entities:
      - sensor.dsb05_multisensor_air_temperature
      - sensor.smartthings_moisture_temperature
      - sensor.multisensor_6_air_temperature
      - sensor.4_in_1_multisensor_air_temperature
  
sensor:
  - platform: template
    sensors:
      temperature_whole_house:
        friendly_name: Whole House Temperature
        unit_of_measurement: '°F'
        value_template: >-
          {% set temp = namespace(sum=0, count=0) %}
          {% for sensor in [
              'sensor.smartthings_moisture_temperature',
              'sensor.multisensor_6_air_temperature'
            ] %}
            {% if states(sensor)|float > 0 %}
              {% set temp.sum = temp.sum + (states(sensor)|float) %}
              {% set temp.count = temp.count + 1 %}
            {% endif %}
          {% endfor %}
          {% if temp.count == 0 %}
            {% set temp.count = 1 %}
          {% endif %}
          {{ (temp.sum / temp.count)|round(1) }}
