#Living room remote
automation:
  - alias: "Ikea Remote 1 Power Button"
    trigger:
      - platform: event
        event_type: zha_event
        event_data:
          device_ieee: "00:0d:6f:ff:fe:4b:6f:12"
          command: "toggle"
    action:
      - data:
          entity_id: group.lights_switches_living_room
        service_template: >-
          {% if is_state("group.lights_switches_living_room", "off") %}
          homeassistant.turn_on
          {% else %}
          homeassistant.turn_off
          {% endif %}
