input_boolean:
  flic_button_single_click:
    name: Flic Button Single Click
    icon: mdi:radio_button_checked

  flic_button_double_click:
    name: Flic Button Double Click
    icon: mdi:radio_button_checked

  flic_button_hold:
    name: Flic Button Hold
    icon: mdi:radio_button_checked

automation:
  - alias: Flic Single Click Action
    trigger:
      - platform: webhook
        webhook_id: flic_single_click
    action:
      - service: homeassistant.toggle
        data:
          entity_id: input_boolean.flic_button_single_click

  - alias: Flic Double Click Action
    trigger:
      - platform: webhook
        webhook_id: flic_double_click
    action:
      - service: homeassistant.toggle
        data:
          entity_id: input_boolean.flic_button_double_click

  - alias: Flic Hold Action
    trigger:
      - platform: webhook
        webhook_id: flic_hold
    action:
      - service: homeassistant.toggle
        data:
          entity_id: input_boolean.flic_button_hold
