# node 34
input_boolean:
  minimote_front_door_1:
    name: Minimote Front Door Button 1 Pushed
    icon: mdi:radio_button_checked
  minimote_front_door_2:
    name: Minimote Front Door Button 1 Held
    icon: mdi:radio_button_checked
  minimote_front_door_3:
    name: Minimote Front Door Button 2 Pushed
    icon: mdi:radio_button_checked
  minimote_front_door_4:
    name: Minimote Front Door Button 2 Held
    icon: mdi:radio_button_checked
  minimote_front_door_5:
    name: Minimote Front Door Button 3 Pushed
    icon: mdi:radio_button_checked
  minimote_front_door_6:
    name: Minimote Front Door Button 3 Held
    icon: mdi:radio_button_checked
  minimote_front_door_7:
    name: Minimote Front Door Button 4 Pushed
    icon: mdi:radio_button_checked
  minimote_front_door_8:
    name: Minimote Front Door Button 4 Held
    icon: mdi:radio_button_checked

automation:
  - alias: Minimote Front Door
    trigger:
      - platform: event
        event_type: zwave_js_event
        event_data:
          node_id: 16 
          home_id: 3996165589
    condition:
      - condition: state
        entity_id: input_boolean.guest_mode
        state: "off"
    action:
      - service: homeassistant.toggle
        data_template:
          entity_id: >
            {% set map = {1: "input_boolean.minimote_front_door_1",
                          2: "input_boolean.minimote_front_door_2",
                          3: "input_boolean.minimote_front_door_3",
                          4: "input_boolean.minimote_front_door_4",
                          5: "input_boolean.minimote_front_door_5",
                          6: "input_boolean.minimote_front_door_6",
                          7: "input_boolean.minimote_front_door_7",
                          8: "input_boolean.minimote_front_door_8"} %}
            {{ map[trigger.event.data.value|int] }}

  - alias: Minimote Front Door Guest Mode
    trigger:
      - platform: event
        event_type: zwave.scene_activated
        event_data:
          entity_id:
            zwave.aeotec_dsa03202_minimote
    condition:
      - condition: state
        entity_id: input_boolean.guest_mode
        state: "on"
    action:
      - service: homeassistant.toggle
        data_template:
          entity_id: >
            {% set map = {1: "light.ge_appliances_zll_light_1b550600_level_on_off",
                          2: "script.guest_lights_off",
                          3: "light.living_room_lamp",
                          4: "script.guest_lights_off",
                          5: "light.aeotec_zw111_nano_dimmer_level_3",
                          6: "script.guest_lights_dim",
                          7: "switch.zooz_zen06_switch",
                          8: "script.guest_lights_on"} %}
            {{ map[trigger.event.data.scene_id|int] }}
