# Accordion Lamp Remote
automation:
  - alias: "Ikea Remote 3 Power Button"
    trigger:
      - platform: event
        event_type: zha_event
        event_data:
          device_ieee: "ec:1b:bd:ff:fe:f4:30:29"
          command: "toggle"
    action:
      - service: homeassistant.toggle
        data:
          entity_id: light.ikea_of_sweden_tradfri_bulb_e26_ws_opal_1000lm_166ca8fe_level_light_color_on_off

  - alias: "Ikea Remote 3 Dim Up Step"
    trigger:
      - platform: event
        event_type: zha_event
        event_data:
          device_ieee: "ec:1b:bd:ff:fe:f4:30:29"
          command: "step_with_on_off"
    action:
      - service: homeassistant.turn_on
        data_template:
          entity_id: light.ikea_of_sweden_tradfri_bulb_e26_ws_opal_1000lm_166ca8fe_level_light_color_on_off
          brightness: >-
            {{ state_attr("light.ikea_of_sweden_tradfri_bulb_e26_ws_opal_1000lm_166ca8fe_level_light_color_on_off", "brightness") + 25 }}

  - alias: "Ikea Remote 3 Dim Down Step"
    trigger:
      - platform: event
        event_type: zha_event
        event_data:
          device_ieee: "ec:1b:bd:ff:fe:f4:30:29"
          command: "step_with_on_off"
    action:
      - service: homeassistant.turn_on
        data_template:
          entity_id: light.ikea_of_sweden_tradfri_bulb_e26_ws_opal_1000lm_166ca8fe_level_light_color_on_off
          brightness: >-
            {{ state_attr("light.ikea_of_sweden_tradfri_bulb_e26_ws_opal_1000lm_166ca8fe_level_light_color_on_off", "brightness") - 25 }}
