# Node 35
input_boolean:
  minimote_master_bedroom_1:
    name: Minimote Master Bedroom Button 1 Pushed
    icon: mdi:radio_button_checked
  minimote_master_bedroom_2:
    name: Minimote Master Bedroom Button 1 Held
    icon: mdi:radio_button_checked
  minimote_master_bedroom_3:
    name: Minimote Master Bedroom Button 2 Pushed
    icon: mdi:radio_button_checked
  minimote_master_bedroom_4:
    name: Minimote Master Bedroom Button 2 Held
    icon: mdi:radio_button_checked
  minimote_master_bedroom_5:
    name: Minimote Master Bedroom Button 3 Pushed
    icon: mdi:radio_button_checked
  minimote_master_bedroom_6:
    name: Minimote Master Bedroom Button 3 Held
    icon: mdi:radio_button_checked
  minimote_master_bedroom_7:
    name: Minimote Master Bedroom Button 4 Pushed
    icon: mdi:radio_button_checked
  minimote_master_bedroom_8:
    name: Minimote Master Bedroom Button 4 Held
    icon: mdi:radio_button_checked

automation:
  - alias: Minimote Master Bedroom
    trigger:
      - platform: event
        event_type: zwave.scene_activated
        event_data:
          entity_id: zwave.aeotec_dsa03202_minimote_2
    action:
      - service: homeassistant.toggle
        data_template:
          entity_id: >
            {% set map = {1: "input_boolean.minimote_master_bedroom_1",
                          2: "input_boolean.minimote_master_bedroom_2",
                          3: "input_boolean.minimote_master_bedroom_3",
                          4: "input_boolean.minimote_master_bedroom_4",
                          5: "input_boolean.minimote_master_bedroom_5",
                          6: "input_boolean.minimote_master_bedroom_6",
                          7: "input_boolean.minimote_master_bedroom_7",
                          8: "input_boolean.minimote_master_bedroom_8"} %}
            {{ map[trigger.event.data.scene_id|int] }}
