input_boolean:
  z_wave_network_ready:
    name: Z-Wave Network Ready
    initial: off
    icon: mdi:z-wave

automation:
  - alias: 'Z-Wave network starting'
    trigger:
      - platform: event
        event_type: zwave.network_start
    action:
      - service: persistent_notification.create
        data:
          title: "Z-Wave"
          message: "Z-Wave network is starting..."
          notification_id: zwave

  - alias: 'Z-Wave network ready'
    trigger:
      - platform: event
        event_type: zwave.network_ready
      - platform: event
        event_type: zwave.network_complete
      - platform: event
        event_type: zwave.network_complete_some_dead
    action:
      - service: homeassistant.turn_on
        entity_id:
          - input_boolean.z_wave_network_ready
      - service: notify.ios_ergisch
        data:
          title: "Z-Wave"
          message: "Network Ready"
      - service: persistent_notification.dismiss
        data:
          notification_id: zwave

  - alias: "Z-Wave network stopped"
    trigger:
      - platform: event
        event_type: zwave.network_stop
    action:
      - service: homeassistant.turn_off
        entity_id:
          - input_boolean.network_ready
